const categories = [
  { _id: 'cat1', name: 'Halal Meat', slug: 'halal-meat', icon: '🥩', description: 'Fresh hand-slaughtered halal meat', displayOrder: 1 },
  { _id: 'cat2', name: 'International Groceries', slug: 'international-groceries', icon: '🛒', description: 'Pakistani, Indian, Bangladeshi & Middle Eastern products', displayOrder: 2 },
  { _id: 'cat3', name: 'KEB Meals', slug: 'keb-meals', icon: '🍛', description: 'Authentic ready-to-heat Pakistani meals', displayOrder: 3 },
  { _id: 'cat4', name: 'Fragrance Bazaar', slug: 'fragrance-bazaar', icon: '🌸', description: 'Premium Arabian perfumes & attars', displayOrder: 4 },
  { _id: 'cat5', name: 'Aayat Collections', slug: 'aayat-collections', icon: '🧕', description: 'Premium hijabs & modest essentials', displayOrder: 5 },
];

const subcategories = [
  { _id: 'sub1', name: 'Beef Products', slug: 'beef-products', icon: '🐄', parentCategory: 'cat1', displayOrder: 1 },
  { _id: 'sub2', name: 'Chicken Products', slug: 'chicken-products', icon: '🍗', parentCategory: 'cat1', displayOrder: 2 },
  { _id: 'sub3', name: 'Lamb Products', slug: 'lamb-products', icon: '🐑', parentCategory: 'cat1', displayOrder: 3 },
  { _id: 'sub4', name: 'Goat Products', slug: 'goat-products', icon: '🐐', parentCategory: 'cat1', displayOrder: 4 },
  { _id: 'sub5', name: 'Fish Products', slug: 'fish-products', icon: '🐟', parentCategory: 'cat1', displayOrder: 5 },
  { _id: 'sub6', name: 'Duck Products', slug: 'duck-products', icon: '🦆', parentCategory: 'cat1', displayOrder: 6 },
  { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products', icon: '🇵🇰', parentCategory: 'cat2', cuisine: 'pakistani', displayOrder: 1 },
  { _id: 'sub10', name: 'Indian Products', slug: 'indian-products', icon: '🇮🇳', parentCategory: 'cat2', cuisine: 'indian', displayOrder: 2 },
  { _id: 'sub11', name: 'Bangladeshi Products', slug: 'bangladeshi-products', icon: '🇧🇩', parentCategory: 'cat2', cuisine: 'bangladeshi', displayOrder: 3 },
  { _id: 'sub12', name: 'Middle Eastern Products', slug: 'middle-eastern-products', icon: '🇸🇦', parentCategory: 'cat2', cuisine: 'middle-eastern', displayOrder: 4 },
  { _id: 'sub13', name: 'Snacks', slug: 'snacks', icon: '🍿', parentCategory: 'cat2', displayOrder: 5 },
  { _id: 'sub14', name: 'Spices', slug: 'spices', icon: '🧂', parentCategory: 'cat2', displayOrder: 6 },
  { _id: 'sub16', name: 'Rice', slug: 'rice', icon: '🍚', parentCategory: 'cat2', displayOrder: 8 },
  { _id: 'sub18', name: "Men's Fragrances", slug: 'mens-fragrances', icon: '🚹', parentCategory: 'cat4', displayOrder: 1 },
  { _id: 'sub19', name: "Women's Fragrances", slug: 'womens-fragrances', icon: '🚺', parentCategory: 'cat4', displayOrder: 2 },
  { _id: 'sub20', name: 'Unisex Fragrances', slug: 'unisex-fragrances', icon: '⚧️', parentCategory: 'cat4', displayOrder: 3 },
  { _id: 'sub21', name: 'Attars & Perfume Oils', slug: 'attars-perfume-oils', icon: '💧', parentCategory: 'cat4', displayOrder: 4 },
  { _id: 'sub25', name: 'Premium Hijabs', slug: 'premium-hijabs', icon: '🧕', parentCategory: 'cat5', displayOrder: 1 },
  { _id: 'sub26', name: 'Prayer Sets', slug: 'prayer-sets', icon: '🤲', parentCategory: 'cat5', displayOrder: 2 },
  { _id: 'sub27', name: 'Prayer Mats', slug: 'prayer-mats', icon: '🕌', parentCategory: 'cat5', displayOrder: 3 },
];

const products = [
  // Beef
  { _id: 'p1', name: 'Halal Beef Mince (500g)', slug: 'halal-beef-mince-500g', description: 'Fresh halal beef mince, hand-slaughtered. Perfect for kebabs, pasta, and curries.', price: 12.99, category: { _id: 'sub1', name: 'Beef Products', slug: 'beef-products' }, image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&h=600&fit=crop', stock: 50, isFeatured: true, tags: ['beef', 'mince', 'halal'] },
  { _id: 'p2', name: 'Beef Rump Steak (1kg)', slug: 'beef-rump-steak-1kg', description: 'Premium cut beef rump steak, aged for tenderness.', price: 28.99, originalPrice: 32.99, category: { _id: 'sub1', name: 'Beef Products', slug: 'beef-products' }, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=600&fit=crop', stock: 30, isOnSale: true, tags: ['beef', 'steak'] },
  { _id: 'p3', name: 'Beef Karahi Cut (1kg)', slug: 'beef-karahi-cut-1kg', description: 'Perfect for Pakistani karahi, tender and flavourful.', price: 18.99, category: { _id: 'sub1', name: 'Beef Products', slug: 'beef-products' }, image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=600&h=600&fit=crop', stock: 40, tags: ['beef', 'karahi'] },
  { _id: 'p4', name: 'Beef Biryani Cut (1kg)', slug: 'beef-biryani-cut-1kg', description: 'Ideal for authentic biryani with bone-in pieces.', price: 17.99, category: { _id: 'sub1', name: 'Beef Products', slug: 'beef-products' }, image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&h=600&fit=crop', stock: 35, tags: ['beef', 'biryani'] },
  { _id: 'p5', name: 'Beef Nihari Cut (1kg)', slug: 'beef-nihari-cut-1kg', description: 'Special nihari cut with bones for rich slow-cooked stew.', price: 15.99, category: { _id: 'sub1', name: 'Beef Products', slug: 'beef-products' }, image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&h=600&fit=crop', stock: 25, isNew: true, tags: ['beef', 'nihari'] },
  // Chicken
  { _id: 'p6', name: 'Whole Chicken (1.5kg)', slug: 'whole-chicken-1500g', description: 'Fresh whole halal chicken, hand-slaughtered.', price: 9.99, category: { _id: 'sub2', name: 'Chicken Products', slug: 'chicken-products' }, image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&h=600&fit=crop', stock: 60, isFeatured: true, tags: ['chicken', 'whole'] },
  { _id: 'p7', name: 'Chicken Breast Boneless (500g)', slug: 'chicken-breast-boneless-500g', description: 'Boneless chicken breast fillets, lean and tender.', price: 11.99, category: { _id: 'sub2', name: 'Chicken Products', slug: 'chicken-products' }, image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&h=600&fit=crop', stock: 45, tags: ['chicken', 'breast'] },
  { _id: 'p8', name: 'Chicken Tikka Pieces (500g)', slug: 'chicken-tikka-pieces-500g', description: 'Marinated chicken tikka ready to cook on BBQ or oven.', price: 13.99, category: { _id: 'sub2', name: 'Chicken Products', slug: 'chicken-products' }, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&h=600&fit=crop', stock: 35, isFeatured: true, tags: ['chicken', 'tikka'] },
  { _id: 'p9', name: 'Chicken Mince (500g)', slug: 'chicken-mince-500g', description: 'Lean chicken mince for healthy meals.', price: 8.99, category: { _id: 'sub2', name: 'Chicken Products', slug: 'chicken-products' }, image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=600&fit=crop', stock: 50, tags: ['chicken', 'mince'] },
  // Lamb
  { _id: 'p10', name: 'Lamb Mince (500g)', slug: 'lamb-mince-500g', description: 'Fresh halal lamb mince, premium quality.', price: 14.99, category: { _id: 'sub3', name: 'Lamb Products', slug: 'lamb-products' }, image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&h=600&fit=crop&q=80', stock: 40, tags: ['lamb', 'mince'] },
  { _id: 'p11', name: 'Lamb Chops (500g)', slug: 'lamb-chops-500g', description: 'Premium lamb cutlets, perfect for grilling.', price: 22.99, originalPrice: 26.99, category: { _id: 'sub3', name: 'Lamb Products', slug: 'lamb-products' }, image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=600&fit=crop&q=80', stock: 25, isFeatured: true, isOnSale: true, tags: ['lamb', 'chops'] },
  { _id: 'p12', name: 'Lamb Shoulder (1kg)', slug: 'lamb-shoulder-1kg', description: 'Whole lamb shoulder for slow roasting.', price: 24.99, category: { _id: 'sub3', name: 'Lamb Products', slug: 'lamb-products' }, image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&h=600&fit=crop', stock: 20, tags: ['lamb', 'shoulder'] },
  // Goat
  { _id: 'p13', name: 'Goat Curry Cut (1kg)', slug: 'goat-curry-cut-1kg', description: 'Fresh goat meat curry cut, halal certified.', price: 21.99, category: { _id: 'sub4', name: 'Goat Products', slug: 'goat-products' }, image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=600&fit=crop&q=80', stock: 30, tags: ['goat', 'curry'] },
  { _id: 'p14', name: 'Goat Mince (500g)', slug: 'goat-mince-500g', description: 'Lean goat mince for traditional recipes.', price: 16.99, category: { _id: 'sub4', name: 'Goat Products', slug: 'goat-products' }, image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&h=600&fit=crop&q=90', stock: 20, tags: ['goat', 'mince'] },
  // Fish
  { _id: 'p15', name: 'Barramundi Fillet (500g)', slug: 'barramundi-fillet-500g', description: 'Fresh barramundi fillets, boneless.', price: 16.99, category: { _id: 'sub5', name: 'Fish Products', slug: 'fish-products' }, image: 'https://images.unsplash.com/photo-1510130113356-d4c9f0e5c96c?w=600&h=600&fit=crop', stock: 25, tags: ['fish', 'barramundi'] },
  { _id: 'p16', name: 'Pomfret Whole (400g)', slug: 'pomfret-whole-400g', description: 'Whole pomfret fish, fresh and clean.', price: 14.99, category: { _id: 'sub5', name: 'Fish Products', slug: 'fish-products' }, image: 'https://images.unsplash.com/photo-1534604973900-c43a0f39c1b7?w=600&h=600&fit=crop', stock: 15, tags: ['fish', 'pomfret'] },
  // Duck
  { _id: 'p17', name: 'Whole Duck (1.8kg)', slug: 'whole-duck-1800g', description: 'Fresh whole duck for roasting.', price: 19.99, category: { _id: 'sub6', name: 'Duck Products', slug: 'duck-products' }, image: 'https://images.unsplash.com/photo-1432139509613-5c4255a1d197?w=600&h=600&fit=crop', stock: 15, tags: ['duck'] },
  // Pakistani Grocery
  { _id: 'p18', name: 'National Biryani Masala', slug: 'national-biryani-masala', description: 'Authentic Pakistani biryani spice mix by National.', price: 3.99, category: { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products' }, image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop', stock: 100, isFeatured: true, tags: ['pakistani', 'masala', 'biryani'] },
  { _id: 'p19', name: 'Shan Karahi Masala', slug: 'shan-karahi-masala', description: 'Perfect karahi every time with Shan.', price: 3.49, category: { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products' }, image: 'https://images.unsplash.com/photo-1599909631498-32e07b66b2a6?w=600&h=600&fit=crop', stock: 80, tags: ['pakistani', 'masala', 'karahi'] },
  { _id: 'p20', name: 'National Chicken Tikka', slug: 'national-chicken-tikka', description: 'Chicken tikka spice mix, easy to use.', price: 3.29, category: { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products' }, image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop&q=80', stock: 70, tags: ['pakistani', 'tikka'] },
  { _id: 'p21', name: 'Tapal Danedar Chai (500g)', slug: 'tapal-danedar-chai', description: 'Premium Pakistani tea leaves, rich flavour.', price: 7.99, category: { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products' }, image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&h=600&fit=crop', stock: 60, isNew: true, tags: ['pakistani', 'chai', 'tea'] },
  { _id: 'p22', name: "Mitchell's Mango Chutney (300g)", slug: 'mitchells-mango-chutney', description: 'Sweet and tangy mango chutney.', price: 4.49, category: { _id: 'sub9', name: 'Pakistani Products', slug: 'pakistani-products' }, image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=600&h=600&fit=crop', stock: 45, tags: ['pakistani', 'chutney'] },
  // Indian Grocery
  { _id: 'p23', name: 'MDH Chana Masala', slug: 'mdh-chana-masala', description: 'Authentic chole masala blend by MDH.', price: 3.99, category: { _id: 'sub10', name: 'Indian Products', slug: 'indian-products' }, image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop&q=90', stock: 70, tags: ['indian', 'masala'] },
  { _id: 'p24', name: 'Basmati Rice 5kg (India Gate)', slug: 'basmati-rice-india-gate', description: 'Premium aged basmati rice, extra long grain.', price: 18.99, category: { _id: 'sub16', name: 'Rice', slug: 'rice' }, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=600&fit=crop', stock: 40, isFeatured: true, tags: ['indian', 'rice'] },
  { _id: 'p25', name: "Haldiram's Bhujia (200g)", slug: 'haldirams-bhujia', description: 'Crunchy spiced snack, perfect with chai.', price: 3.99, category: { _id: 'sub13', name: 'Snacks', slug: 'snacks' }, image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&h=600&fit=crop', stock: 55, tags: ['indian', 'snack'] },
  // Middle Eastern
  { _id: 'p26', name: 'Al Marai Feta Cheese (200g)', slug: 'al-marai-feta-cheese', description: 'Creamy feta cheese, perfect for salads.', price: 5.99, category: { _id: 'sub12', name: 'Middle Eastern Products', slug: 'middle-eastern-products' }, image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&h=600&fit=crop', stock: 30, tags: ['middle-eastern', 'cheese'] },
  { _id: 'p27', name: 'Tahina Paste (300g)', slug: 'tahina-paste-300g', description: 'Premium sesame paste for hummus and dressings.', price: 5.49, category: { _id: 'sub12', name: 'Middle Eastern Products', slug: 'middle-eastern-products' }, image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop', stock: 35, tags: ['middle-eastern', 'tahina'] },
  // Snacks
  { _id: 'p28', name: 'Lays Classic Salted (170g)', slug: 'lays-classic-salted', description: 'Classic salted potato chips.', price: 3.49, category: { _id: 'sub13', name: 'Snacks', slug: 'snacks' }, image: 'https://images.unsplash.com/photo-1566473782167-9f81f36f4f65?w=600&h=600&fit=crop', stock: 100, tags: ['snack', 'chips'] },
  // KEB Meals
  { _id: 'p29', name: 'Karachi Chicken Biryani (500g)', slug: 'karachi-chicken-biryani', description: 'Ready-to-heat authentic Karachi style biryani.', price: 14.99, category: { _id: 'cat3', name: 'KEB Meals', slug: 'keb-meals' }, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=600&fit=crop', stock: 40, isFeatured: true, tags: ['keb', 'biryani', 'ready-meal'] },
  { _id: 'p30', name: 'Karachi Beef Biryani (500g)', slug: 'karachi-beef-biryani', description: 'Rich beef biryani, ready to heat and serve.', price: 15.99, category: { _id: 'cat3', name: 'KEB Meals', slug: 'keb-meals' }, image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&h=600&fit=crop', stock: 35, isFeatured: true, tags: ['keb', 'biryani'] },
  { _id: 'p31', name: 'Charsi Chicken Karahi (400g)', slug: 'charsi-chicken-karahi', description: 'Charsi style chicken karahi, traditional recipe.', price: 13.99, category: { _id: 'cat3', name: 'KEB Meals', slug: 'keb-meals' }, image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=600&fit=crop', stock: 30, isNew: true, tags: ['keb', 'karahi'] },
  { _id: 'p32', name: 'Shahi White Chicken Karahi (400g)', slug: 'shahi-white-chicken-karahi', description: 'Creamy white karahi with rich flavour.', price: 14.49, category: { _id: 'cat3', name: 'KEB Meals', slug: 'keb-meals' }, image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=600&fit=crop', stock: 25, tags: ['keb', 'karahi'] },
  // Fragrances - Men
  { _id: 'p33', name: 'Lattafa Raghba for Men (100ml)', slug: 'lattafa-raghba-men', description: 'Popular Arabian fragrance for men with oriental notes.', price: 45.99, category: { _id: 'sub18', name: "Men's Fragrances", slug: 'mens-fragrances' }, image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&h=600&fit=crop', stock: 20, isFeatured: true, tags: ['fragrance', 'men', 'lattafa'] },
  { _id: 'p34', name: 'Armaf Club De Nuit Intense (105ml)', slug: 'armaf-club-de-nuit', description: "Premium men's EDP, long lasting.", price: 55.99, originalPrice: 65.99, category: { _id: 'sub18', name: "Men's Fragrances", slug: 'mens-fragrances' }, image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=600&fit=crop', stock: 15, isOnSale: true, tags: ['fragrance', 'men', 'armaf'] },
  { _id: 'p35', name: 'Afnan Supremacy Silver (100ml)', slug: 'afnan-supremacy-silver', description: 'Fresh aquatic fragrance for modern men.', price: 39.99, category: { _id: 'sub18', name: "Men's Fragrances", slug: 'mens-fragrances' }, image: 'https://images.unsplash.com/photo-1594035910387-fbd1a485b12e?w=600&h=600&fit=crop', stock: 25, tags: ['fragrance', 'men', 'afnan'] },
  { _id: 'p36', name: "Al Haramain L'Aventure (100ml)", slug: 'al-haramain-laventure', description: 'Adventure inspired scent for bold men.', price: 49.99, category: { _id: 'sub18', name: "Men's Fragrances", slug: 'mens-fragrances' }, image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop', stock: 18, isNew: true, tags: ['fragrance', 'men', 'al-haramain'] },
  // Fragrances - Women
  { _id: 'p37', name: 'Lattafa Yara for Women (100ml)', slug: 'lattafa-yara-women', description: 'Sweet floral Arabian perfume for women.', price: 42.99, category: { _id: 'sub19', name: "Women's Fragrances", slug: 'womens-fragrances' }, image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=600&fit=crop', stock: 20, isFeatured: true, tags: ['fragrance', 'women', 'lattafa'] },
  { _id: 'p38', name: 'Armaf Treselle EDP (100ml)', slug: 'armaf-treselle', description: "Elegant women's fragrance for special occasions.", price: 48.99, category: { _id: 'sub19', name: "Women's Fragrances", slug: 'womens-fragrances' }, image: 'https://images.unsplash.com/photo-1592945832076-3a088315cbbf?w=600&h=600&fit=crop', stock: 15, tags: ['fragrance', 'women', 'armaf'] },
  // Fragrances - Unisex
  { _id: 'p39', name: 'French Avenue Liquid Brun (100ml)', slug: 'french-avenue-liquid-brun', description: 'Unisex woody fragrance, modern and elegant.', price: 52.99, category: { _id: 'sub20', name: 'Unisex Fragrances', slug: 'unisex-fragrances' }, image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&h=600&fit=crop', stock: 12, tags: ['fragrance', 'unisex', 'french-avenue'] },
  { _id: 'p40', name: 'Arabiyat Prestige Maya (100ml)', slug: 'arabiyat-prestige-maya', description: 'Floral unisex fragrance, versatile and long-lasting.', price: 38.99, category: { _id: 'sub20', name: 'Unisex Fragrances', slug: 'unisex-fragrances' }, image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&h=600&fit=crop', stock: 20, tags: ['fragrance', 'unisex', 'arabiyat'] },
  // Attars
  { _id: 'p41', name: 'Al Haramain Oud Muattar (50g)', slug: 'al-haramain-oud-muattar', description: 'Pure oud incense, premium quality.', price: 35.99, category: { _id: 'sub21', name: 'Attars & Perfume Oils', slug: 'attars-perfume-oils' }, image: 'https://images.unsplash.com/photo-1547793548-7a00406e2873?w=600&h=600&fit=crop', stock: 15, tags: ['attar', 'oud'] },
  // Aayat
  { _id: 'p42', name: 'Premium Chiffon Hijab - Black', slug: 'premium-chiffon-hijab-black', description: 'Lightweight premium chiffon hijab, elegant drape.', price: 19.99, category: { _id: 'sub25', name: 'Premium Hijabs', slug: 'premium-hijabs' }, image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=600&fit=crop', stock: 50, isFeatured: true, tags: ['hijab', 'chiffon'] },
  { _id: 'p43', name: 'Bamboo Jersey Hijab - Navy', slug: 'bamboo-jersey-hijab-navy', description: 'Soft bamboo jersey hijab, comfortable all day.', price: 22.99, category: { _id: 'sub25', name: 'Premium Hijabs', slug: 'premium-hijabs' }, image: 'https://images.unsplash.com/photo-1607349913338-fca6f7fc608a?w=600&h=600&fit=crop', stock: 40, tags: ['hijab', 'jersey'] },
  { _id: 'p44', name: 'Prayer Set - Rose Gold', slug: 'prayer-set-rose-gold', description: 'Complete prayer set with bag, premium quality.', price: 34.99, category: { _id: 'sub26', name: 'Prayer Sets', slug: 'prayer-sets' }, image: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=600&h=600&fit=crop', stock: 25, isFeatured: true, tags: ['prayer', 'set'] },
  { _id: 'p45', name: 'Premium Prayer Mat - Teal', slug: 'premium-prayer-mat-teal', description: 'Luxurious prayer mat with soft texture.', price: 29.99, category: { _id: 'sub27', name: 'Prayer Mats', slug: 'prayer-mats' }, image: 'https://images.unsplash.com/photo-1542816417-0983c9c0ad53?w=600&h=600&fit=crop', stock: 30, tags: ['prayer', 'mat'] },
];

export { categories, subcategories, products };
